# Generated by Django 4.0.5 on 2022-07-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('Youtube', 'Youtube'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Newsletter', 'Newsletter'), ('Other', 'Other')], max_length=100)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.affiliation')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Qualified', 'Qualified'), ('Contacted', 'Contacted'), ('Conversion', 'Conversion'), ('Converted', 'Converted')], default='New', max_length=40)),
                ('last_status_update', models.DateTimeField(auto_now_add=True)),
                ('public_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('private_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
