# Generated by Django 4.0.5 on 2022-08-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='private_note',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='public_note',
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
