# Generated by Django 4.0.5 on 2022-07-06 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_user_is_agent_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='affiliation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leads.affiliation'),
            preserve_default=False,
        ),
    ]
