# Generated by Django 4.0.5 on 2022-07-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Qualified', 'Qualified'), ('Contacted', 'Contacted'), ('Conversion', 'Conversion'), ('Converted', 'Converted')], default='New', max_length=40)),
                ('last_status_update', models.DateTimeField(auto_now_add=True)),
                ('public_note', models.CharField(max_length=1000, null=True)),
                ('private_note', models.CharField(max_length=1000, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
