# Generated by Django 4.0.5 on 2022-07-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='user',
            new_name='owner',
        ),
    ]
